version: 2
jobs:
  build:
    docker:
      - image: circleci/node:11
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package-lock.json" }}
      - run: npm ci
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package-lock.json" }}
      - run: npm t && cat ./coverage/lcov.info | npx coveralls && rm -rf ./coverage
      - run: npm run build
